#pragma once

typedef enum VALIDATION_TYPE {
	TYPE_V_REGEX,
	TYPE_V_UNKOWN,
} E_VALIDATION_TYPE;

typedef enum RELETIONSHIP_VALID_TYPE {
	TYPE_R_DATE,
	TYPE_R_ON,
	TYPE_R_OFF,
} E_RELETIONSHIP_VALID_TYPE;
